export const companyNames = [
  "Aon",
  "Wuri",
  "Dropbox",
  "Apple",
  "Weekday",
  "Google",
  "Weyland-Yutani Corporation",
  "InGen",
  "Virtucon",
  "Oscorp Industries",
  "Tyrell Corporation",
  "Dunder Mifflin",
  "Vandalay Industries",
  "Spacely Sprockets",
  "Gringotts Wizarding Bank",
  "Monsters, Inc.",
  "Aperture Science",
  "Massive Dynamic",
  "Aon",
  "Wuri",
  "Dropbox",
  "Apple",
  "Weekday",
  "Google",
  "Warbucks Industries",
  "Sirius Cybernetics Corporation",
  "Soylent Corporation",
  "Sirius Cybernetics Corporation",
  "Blue Sun Corporation",
  "Strickland Propane",
  "Gekko & Co",
  "The Three Broomsticks",
  "The Daily Planet",
  "The Bluth Company",
  "The Galactic Empire",
  "The Rebel Alliance",
  "The Ministry of Magic",
  "The Galactic Senate",
  "The Jedi Order",
  "The Sith Order",
  "The First Order",
  "The Resistance",
  "The Citadel",
  "The Company",
  "Aon",
  "Wuri",
  "Dropbox",
  "Apple",
  "Weekday",
  "Google",
  "The Umbrella Academy",
  "The Hand",
  "The Corporation",
  "The League of Assassins",
  "The Guild",
  "The Alliance",
  "The Syndicate",
  "The Combine",
  "The Foundation",
  "The Organization",
  "The Syndicate",
  "The Corporation",
  "The Guild",
  "The Company",
  "The Umbrella Academy",
  "The Hand",
  "The League of Assassins",
  "The Guild",
  "The Alliance",
  "The Syndicate",
  "The Combine",
  "The Foundation",
  "The Organization",
  "The Syndicate",
  "The Corporation",
  "The Guild",
  "The Company",
  "Apple",
  "The Hand",
  "The Alliance",
  "The Syndicate",
  "The Combine",
  "The Foundation",
  "The Organization",
  "The Syndicate",
  "The Corporation",
  "The Guild",
  "The Company",
  "The Umbrella Academy",
  "The Hand",
  "The League of Assassins",
  "The Guild",
  "The Alliance",
  "The Syndicate",
  "The Combine",
  "The Foundation",
  "The Organization",
  "The Syndicate",
  "The Corporation",
  "The Guild",
  "The Company",
  "The Umbrella Academy",
  "The Hand",
  "The League of Assassins",
  "The Guild",
  "The Alliance",
  "The Syndicate",
  "The Combine",
  "The Foundation",
  "The Organization",
  "The Syndicate",
  "The Corporation",
];
